### ISSUE TITLE
Possible credential leak?

### ISSUE THREAD

**Issue by albertyw** [vastbinderj/dotfiles#1]
I noticed what would appear to be a plaintext password on https://github.com/vastbinderj/dotfiles/blob/master/.gitconfig#L13.  It looks like the username/password combo doesn't work thankfully.  May I recommend trying something like https://github.com/albertyw/dotfiles/blob/master/files/gitconfig#L67 to keep your credentials out of your repo?

**Comment by vastbinderj** [comment]
That is a better idea. I will change it. Thanks for bring this to my
attention. I appreciate your follow up.

James

**Comment by albertyw** [comment]
Looks like it's been fixed in 1e569ea89f8c4d3e54837cba96c50e9ad4ed5130
